Feature/sprint 3.0
DariaDostoevskaia/Space pull request #4
Opened 2023-04-01 19:20 UTC by DariaDostoevskaia

2023-04-01 19:20 UTC, DariaDostoevskaia commented
not ready

2023-04-02 12:30 UTC, Overlordshor requested changes

2023-04-02 12:30 UTC, Overlordshor commented on Assets/Scripts/EnemyShip.cs
> +    private Vector3 _movement;
Why is it in the enemy ship class?
The task was to create a ship player 2, which will be an ally of player 1

2023-04-02 12:30 UTC, Overlordshor commented on Assets/Scripts/EnemyShip.cs
> +        //    transform.rotation *= Quaternion.Euler(0f, 360f * Time.deltaTime, 0f);
commented code should not be in a pull request

2023-04-02 12:30 UTC, Overlordshor commented on Assets/Scripts/EnemyShip.cs
> +    //}
remove

2023-04-02 12:30 UTC, Overlordshor commented on Assets/Scripts/Sample.cs
> +        }
Missing:
1. Generating random vectors
2. Adding elements to the list.
3. Vector addition
4. Removal of vectors.

2023-04-05 18:31 UTC, closed without merging